// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufxseuwpchzqfkzefcng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmeHNldXdwY2h6cWZremVmY25nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDI5NDAsImV4cCI6MjA2MDU3ODk0MH0.cNmQ3ga4OrtLY00BQXAEjulA_kWbD7-V1zf4ciJm6ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);